const digitalInstrumentGenerators = [
        // --- BATCH GENERATED FROM CSV ---

    () => {
        return {
            topic: "Electronic Displays",
            question: "What defines a 'pixel' in a modern Electronic Flight Instrument System (EFIS) LCD display?",
            options: ["A localized vacuum tube emitting light", "A singular phosphor dot excited by an electron beam", "A magnetic coil used to deflect light"],
            correct: "The smallest addressable programmable element of a picture on the screen"
            };
        },
            () => {
        return {
            topic: "Electronic Displays",
            question: "In an aircraft CRT display, what is the specific function of the shadow mask?",
            options: ["To block ambient glare from the cockpit", "To filter out electromagnetic interference (EMI)", "To regulate the voltage of the anode"],
            correct: "To ensure the electron beam only strikes the correct color phosphor dot"
            };
        },
            () => {
        return {
            topic: "Electronic Displays",
            question: "How does a Twisted-Nematic (TN) Liquid Crystal Display control the passage of light?",
            options: ["By heating the liquid crystals until they glow", "By physically moving microscopic mirrors", "By generating internal light using a matrix of LEDs"],
            correct: "By altering the polarization of light as it passes through crystals that untwist when a voltage is applied"
            };
        },
            () => {
        return {
            topic: "Electronic Displays",
            question: "What is the primary advantage of Active-Matrix LCDs (AMLCD) over Passive-Matrix LCDs?",
            options: ["They do not require a backlight", "They are completely immune to static electricity", "They use significantly more power to operate"],
            correct: "Each pixel has its own dedicated transistor, drastically improving refresh rate and contrast"
            };
        },
            () => {
        return {
            topic: "Electronic Displays",
            question: "Which electronic display technology utilizes an array of microscopic diodes that emit their own light, eliminating the need for a separate backlight?",
            options: ["Cathode Ray Tube (CRT)", "Liquid Crystal Display (LCD)", "Plasma Display Panel (PDP)"],
            correct: "Light Emitting Diode (LED) Display"
            };
        },
            () => {
        return {
            topic: "Electronic Displays",
            question: "In a traditional color CRT, how is the electron beam swept across the screen to trace a raster pattern?",
            options: ["By mechanically moving the cathode assembly", "By rotating the screen glass", "By using internal fiber optic cables"],
            correct: "By varying the magnetic fields generated by the deflection coils"
            };
        },
            () => {
        return {
            topic: "Electronic Displays",
            question: "What term describes the number of times per second an EFIS display completely redraws the image on the screen?",
            options: ["Baud Rate", "Aspect Ratio", "Resolution"],
            correct: "Refresh Rate"
            };
        },
            () => {
        return {
            topic: "Electronic Displays",
            question: "In an avionics color CRT, which three phosphor colors are used to produce all visible colors via additive mixing?",
            options: ["Red, Yellow, Blue", "Cyan, Magenta, Yellow", "Black, White, Grey"],
            correct: "Red, Green, Blue"
            };
        },
            () => {
        return {
            topic: "Numbering Systems",
            question: "What is the decimal equivalent of the binary number 10110?",
            options: ["18", "24", "20"],
            correct: "22"
            };
        },
            () => {
        return {
            topic: "Numbering Systems",
            question: "Which numbering system utilizes base 16 and digits 0-9 alongside letters A-F?",
            options: ["Binary", "Octal", "Decimal"],
            correct: "Hexadecimal"
            };
        },
            () => {
        return {
            topic: "Numbering Systems",
            question: "How is the decimal number 25 represented in pure Binary Coded Decimal (BCD)?",
            options: ["11001", "101001", "001000101"],
            correct: "0010 0101"
            };
        },
            () => {
        return {
            topic: "Numbering Systems",
            question: "What is the primary purpose of using the Two's Complement numbering method in digital microprocessors?",
            options: ["To compress data for faster transmission", "To detect errors in RAM", "To convert analog signals to digital"],
            correct: "To represent negative numbers and allow the ALU to perform subtraction using standard addition circuits"
            };
        },
            () => {
        return {
            topic: "Numbering Systems",
            question: "Convert the hexadecimal value 1F to its decimal equivalent.",
            options: ["25", "30", "16"],
            correct: "31"
            };
        },
            () => {
        return {
            topic: "Numbering Systems",
            question: "If an aircraft data word is exactly 8 bits long, what is the maximum decimal value it can represent?",
            options: ["128", "256", "512"],
            correct: "255"
            };
        },
            () => {
        return {
            topic: "Numbering Systems",
            question: "In binary arithmetic, what is the result of adding 101 and 110?",
            options: ["10110", "1001", "1111"],
            correct: "1011"
            };
        },
            () => {
        return {
            topic: "Numbering Systems",
            question: "What does the 'Least Significant Bit' (LSB) represent in a binary data word?",
            options: ["The bit that dictates the sign (positive/negative)", "The bit that triggers a parity error", "The bit transmitted first in a parallel bus"],
            correct: "The bit positioned on the far right, holding the lowest mathematical value"
            };
        },
            () => {
        return {
            topic: "Numbering Systems",
            question: "How many binary bits are required to represent a single Octal digit?",
            options: ["4", "8", "2"],
            correct: "3"
            };
        },
            () => {
        return {
            topic: "Numbering Systems",
            question: "What is the Two's complement of the binary number 0101?",
            options: ["1010", "0110", "1000"],
            correct: "1011"
            };
        },
            () => {
        return {
            topic: "Data Conversion",
            question: "What defines the 'resolution' of an Analog-to-Digital Converter (ADC)?",
            options: ["The speed at which the conversion occurs", "The maximum voltage the ADC can safely accept", "The physical size of the ADC microchip"],
            correct: "The number of discrete digital levels or 'steps' it can divide the analog input into (determined by bit count)"
            };
        },
            () => {
        return {
            topic: "Data Conversion",
            question: "In an ADC, what is the 'quantization error'?",
            options: ["A complete failure of the conversion process", "A voltage spike on the power supply", "A parity error in the output data bus"],
            correct: "The slight difference between the actual analog input value and the nearest available digital step value"
            };
        },
            () => {
        return {
            topic: "Data Conversion",
            question: "According to the Nyquist Sampling Theorem, to accurately digitize an analog signal without aliasing, the sampling rate must be:",
            options: ["Exactly equal to the highest frequency", "At least half the highest frequency", "At least four times the highest frequency"],
            correct: "At least twice the highest frequency of the analog signal"
            };
        },
            () => {
        return {
            topic: "Data Conversion",
            question: "Which Analog-to-Digital Converter (ADC) architecture provides the fastest possible conversion time by using multiple comparators simultaneously?",
            options: ["Successive Approximation", "Integrating", "Delta-Sigma"],
            correct: "Flash (Parallel) ADC"
            };
        },
            () => {
        return {
            topic: "Data Conversion",
            question: "In a Digital-to-Analog Converter (DAC), what circuit configuration is commonly used to weight the digital bits and produce the analog output voltage?",
            options: ["A full-wave rectifier", "A step-up transformer", "A logic NAND gate array"],
            correct: "An R-2R Resistor Ladder"
            };
        },
            () => {
        return {
            topic: "Data Conversion",
            question: "What effect does increasing the number of bits in an ADC have on the resulting digital output?",
            options: ["It decreases the sampling rate", "It increases the maximum input voltage", "It makes the output completely error-free"],
            correct: "It increases the resolution and decreases the quantization error"
            };
        },
            () => {
        return {
            topic: "Data Conversion",
            question: "Multiplexing in an aircraft digital data acquisition system allows:",
            options: ["A single digital word to hold multiple voltages", "A computer to run without RAM", "The conversion of AC power to DC power"],
            correct: "Multiple analog sensor signals to share a single ADC and data bus by taking turns"
            };
        },
            () => {
        return {
            topic: "Data Conversion",
            question: "Successive-Approximation ADCs utilize which internal component to compare the analog input against generated digital equivalents?",
            options: ["An Inductor", "A Microprocessor", "A Multiplexer"],
            correct: "A Digital-to-Analog Converter (DAC)"
            };
        },
            () => {
        return {
            topic: "Data Buses",
            question: "ARINC 429 is a standard commercial aviation data bus. What type of physical transmission line does it use?",
            options: ["A single coaxial cable", "A multi-core optical fiber", "A triaxial cable"],
            correct: "A shielded twisted pair of wires"
            };
        },
            () => {
        return {
            topic: "Data Buses",
            question: "What is the total length of a standard ARINC 429 data word?",
            options: ["16 bits", "8 bits", "64 bits"],
            correct: "32 bits"
            };
        },
            () => {
        return {
            topic: "Data Buses",
            question: "In an ARINC 429 data word, what do the first 8 bits (bits 1-8) define?",
            options: ["The Parity bit", "The Source/Destination Identifier (SDI)", "The Sign/Status Matrix (SSM)"],
            correct: "The Label (identifying the type of data being transmitted)"
            };
        },
            () => {
        return {
            topic: "Data Buses",
            question: "The electrical signal for an ARINC 429 transmission operates on which logic format?",
            options: ["Unipolar Non-Return to Zero (NRZ)", "Manchester II Bi-phase", "Pulse Width Modulation (PWM)"],
            correct: "Bipolar Return to Zero (RZ)"
            };
        },
            () => {
        return {
            topic: "Data Buses",
            question: "What is the maximum data transmission rate for a 'High Speed' ARINC 429 bus?",
            options: ["12.5 kbps", "1 Mbps", "100 Mbps"],
            correct: "100 kbps"
            };
        },
            () => {
        return {
            topic: "Data Buses",
            question: "Which of the following data buses is characterized as a bi-directional, multiple-transmitter data bus that operates without a central bus controller?",
            options: ["ARINC 429", "MIL-STD-1553", "CSDB"],
            correct: "ARINC 629"
            };
        },
            () => {
        return {
            topic: "Data Buses",
            question: "MIL-STD-1553 utilizes a Command/Response architecture. Which component dictates and initiates all data transfers on the bus?",
            options: ["The Remote Terminal (RT)", "The Subsystem Monitor", "The Bus Monitor (BM)"],
            correct: "The Bus Controller (BC)"
            };
        },
            () => {
        return {
            topic: "Data Buses",
            question: "In a MIL-STD-1553 data bus, how many bits long is the synchronization (sync) field of each 20-bit word?",
            options: ["1 bit", "5 bits", "8 bits"],
            correct: "3 bits"
            };
        },
            () => {
        return {
            topic: "Data Buses",
            question: "What encoding method is used in MIL-STD-1553 to ensure the signal is self-clocking and carries no DC bias?",
            options: ["Bipolar Return to Zero", "Unipolar NRZ", "Frequency Shift Keying"],
            correct: "Manchester II Bi-phase"
            };
        },
            () => {
        return {
            topic: "Data Buses",
            question: "The Commercial Standard Digital Bus (CSDB) operates using what physical electrical standard?",
            options: ["RS-232", "ARINC 429", "IEEE 1394"],
            correct: "EIA RS-422 (Differential Serial)"
            };
        },
            () => {
        return {
            topic: "Data Buses",
            question: "How does ARINC 629 resolve bus contention (collisions) without needing a central bus controller?",
            options: ["By using physical switches on the bus", "By assigning a completely separate wire to each transmitter", "By forcing all systems to transmit simultaneously"],
            correct: "By using a strict timing protocol where each terminal waits for specific Time Gaps before transmitting"
            };
        },
            () => {
        return {
            topic: "Data Buses",
            question: "In an ARINC 429 transmission, what is the purpose of the parity bit (bit 32)?",
            options: ["To identify the sender", "To dictate the speed of transmission", "To indicate positive or negative data"],
            correct: "To provide basic error checking by ensuring an odd number of logic '1's in the word"
            };
        },
            () => {
        return {
            topic: "Data Buses",
            question: "What is the primary advantage of the AFDX (ARINC 664) data network over older ARINC 429 systems?",
            options: ["It operates entirely on mechanical linkages", "It is immune to lightning strikes", "It is completely analog"],
            correct: "It utilizes commercial Ethernet technology, providing massively higher bandwidth and deterministic routing"
            };
        },
            () => {
        return {
            topic: "Data Buses",
            question: "In a MIL-STD-1553 system, what component provides the interface between the main data bus and the aircraft subsystem (e.g., a radar or radio)?",
            options: ["The Bus Controller (BC)", "The Bus Monitor (BM)", "The Data Loader"],
            correct: "The Remote Terminal (RT)"
            };
        },
            () => {
        return {
            topic: "Data Buses",
            question: "Which topology best describes an ARINC 429 network?",
            options: ["Ring", "Star", "Mesh"],
            correct: "Simplex (One-way), Point-to-Multipoint"
            };
        },
            () => {
        return {
            topic: "Logic Circuits",
            question: "A logic gate has two inputs. The output is HIGH (1) only when both inputs are HIGH. What type of gate is this?",
            options: ["OR", "NAND", "NOR"],
            correct: "AND"
            };
        },
            () => {
        return {
            topic: "Logic Circuits",
            question: "A logic gate outputs LOW (0) only when all its inputs are HIGH. What gate is this?",
            options: ["AND", "OR", "XOR"],
            correct: "NAND"
            };
        },
            () => {
        return {
            topic: "Logic Circuits",
            question: "Which logic gate functions as an exclusive 'OR', outputting HIGH only when its inputs are different from each other?",
            options: ["NAND", "NOR", "XNOR"],
            correct: "XOR"
            };
        },
            () => {
        return {
            topic: "Logic Circuits",
            question: "In Boolean algebra, what does the expression 'A + B' mathematically represent?",
            options: ["A AND B", "A NOT B", "A XOR B"],
            correct: "A OR B"
            };
        },
            () => {
        return {
            topic: "Logic Circuits",
            question: "What is the primary function of a basic RS (Reset-Set) Flip-Flop circuit?",
            options: ["To act as an amplifier", "To convert AC to DC", "To divide the clock frequency by 10"],
            correct: "To act as a basic 1-bit memory storage device (a latch)"
            };
        },
            () => {
        return {
            topic: "Logic Circuits",
            question: "How does a J-K Flip-Flop overcome the 'invalid' state found in a basic RS Flip-Flop?",
            options: ["By removing the clock input", "By using resistors instead of transistors", "By requiring three inputs"],
            correct: "By toggling its output state when both inputs are HIGH, instead of locking up"
            };
        },
            () => {
        return {
            topic: "Logic Circuits",
            question: "In digital logic circuits, what is a Shift Register used for?",
            options: ["To convert analog signals to digital", "To amplify logic levels", "To generate clock pulses"],
            correct: "To temporarily store data and shift it serially bit-by-bit (e.g., parallel-to-serial conversion)"
            };
        },
            () => {
        return {
            topic: "Logic Circuits",
            question: "What type of logic circuit is designed to select one of several input lines and route it to a single output line based on control signals?",
            options: ["Demultiplexer", "Adder", "Decoder"],
            correct: "Multiplexer"
            };
        },
            () => {
        return {
            topic: "Logic Circuits",
            question: "What is a 'Half-Adder' logic circuit capable of doing?",
            options: ["Adding three binary bits with a carry-in", "Subtracting two binary bits", "Multiplying two binary bits"],
            correct: "Adding two binary bits and producing a sum and a carry-out"
            };
        },
            () => {
        return {
            topic: "Logic Circuits",
            question: "What is the fundamental difference between combinational logic and sequential logic?",
            options: ["Combinational logic uses analog voltages; sequential uses digital.", "Combinational logic requires a clock; sequential does not.", "Combinational logic only uses AND gates; sequential uses OR gates."],
            correct: "Sequential logic has memory (its output depends on present inputs AND past states), while combinational logic does not."
            };
        },
            () => {
        return {
            topic: "Logic Circuits",
            question: "Which logic gate is functionally equivalent to an AND gate followed immediately by a NOT gate?",
            options: ["OR", "NOR", "XOR"],
            correct: "NAND"
            };
        },
            () => {
        return {
            topic: "Logic Circuits",
            question: "In standard 5V TTL (Transistor-Transistor Logic), what voltage range typically defines a valid logic HIGH (1) input state?",
            options: ["0V to 0.8V", "-5V to 0V", "1.5V to 2.0V"],
            correct: "2.0V to 5.0V"
            };
        },
            () => {
        return {
            topic: "Logic Circuits",
            question: "An exclusive-NOR (XNOR) gate will output a HIGH state when:",
            options: ["Any input is HIGH", "The inputs are different", "All inputs are LOW"],
            correct: "The inputs are identical (e.g., both 0 or both 1)"
            };
        },
            () => {
        return {
            topic: "Logic Circuits",
            question: "What is the purpose of a clock signal in synchronous digital logic circuits?",
            options: ["To provide power to the ICs", "To measure the ambient temperature", "To convert digital signals to analog"],
            correct: "To provide a master timing pulse that synchronizes all state changes across the system"
            };
        },
            () => {
        return {
            topic: "Logic Circuits",
            question: "Which flip-flop toggle state changes its output state on every active clock edge if its input is held HIGH?",
            options: ["D Flip-Flop", "RS Flip-Flop", "Master-Slave Flip-Flop"],
            correct: "T (Toggle) Flip-Flop"
            };
        },
            () => {
        return {
            topic: "Computer Structure",
            question: "In a basic computer system architecture, what is the primary function of the CPU?",
            options: ["To store long-term data", "To power the mother board", "To convert analog signals to digital"],
            correct: "To fetch, decode, and execute program instructions and process data"
            };
        },
            () => {
        return {
            topic: "Computer Structure",
            question: "What type of computer memory is non-volatile and cannot be modified by the user or the program during normal flight operations?",
            options: ["SRAM", "DRAM", "Cache"],
            correct: "ROM (Read-Only Memory)"
            };
        },
            () => {
        return {
            topic: "Computer Structure",
            question: "Which type of memory requires constant electrical refreshing to maintain its stored data because it uses tiny capacitors?",
            options: ["ROM", "PROM", "SRAM"],
            correct: "Dynamic RAM (DRAM)"
            };
        },
            () => {
        return {
            topic: "Computer Structure",
            question: "What is the purpose of the 'Address Bus' in a microprocessor system?",
            options: ["To carry the actual data being processed", "To provide power to the memory chips", "To carry control signals like Read/Write"],
            correct: "To carry binary numbers from the CPU that specify which memory location or I/O port is to be accessed"
            };
        },
            () => {
        return {
            topic: "Computer Structure",
            question: "The 'Data Bus' in a typical microcomputer architecture is:",
            options: ["Unidirectional, moving only from CPU to RAM", "Analog, carrying varying voltages", "Serial, moving one bit at a time"],
            correct: "Bi-directional, allowing data to flow into and out of the CPU"
            };
        },
            () => {
        return {
            topic: "Computer Structure",
            question: "What is an EEPROM?",
            options: ["A memory chip that requires a UV light to erase", "A volatile memory chip that loses data when power is removed", "A mechanical hard drive"],
            correct: "Electrically Erasable Programmable Read-Only Memory (can be wiped and rewritten electronically)"
            };
        },
            () => {
        return {
            topic: "Computer Structure",
            question: "In computer architecture, what does the term 'Byte' refer to?",
            options: ["A single 1 or 0", "A 4-bit word", "A 32-bit word"],
            correct: "A grouping of exactly 8 bits"
            };
        },
            () => {
        return {
            topic: "Computer Structure",
            question: "What is the function of the 'Control Bus' in a microcomputer?",
            options: ["To act as the master power switch", "To carry data to the monitor", "To identify the IP address of the computer"],
            correct: "To carry timing and command signals (like Read, Write, and Interrupt) between the CPU and other components"
            };
        },
            () => {
        return {
            topic: "Computer Structure",
            question: "Which component within a CPU performs actual mathematical calculations and logic comparisons?",
            options: ["The Program Counter", "The Instruction Decoder", "The Accumulator"],
            correct: "The Arithmetic Logic Unit (ALU)"
            };
        },
            () => {
        return {
            topic: "Computer Structure",
            question: "What type of memory is used as an ultra-fast buffer located directly inside or adjacent to the CPU to speed up processing?",
            options: ["EEPROM", "Virtual Memory", "Flash Memory"],
            correct: "Cache Memory"
            };
        },
            () => {
        return {
            topic: "Computer Structure",
            question: "In a microcontroller, what is the 'Watchdog Timer' designed to do?",
            options: ["To keep track of the time of day (UTC)", "To measure the duration of a flight", "To slow down the CPU to save power"],
            correct: "To automatically reset the microprocessor if the software crashes or hangs in an infinite loop"
            };
        },
            () => {
        return {
            topic: "Computer Structure",
            question: "Which of the following accurately describes 'Firmware'?",
            options: ["The physical metal casing of the computer", "Software that is constantly changing and rewriting itself", "Removable storage like a USB drive"],
            correct: "Software that is permanently programmed into a hardware ROM or flash memory chip"
            };
        },
            () => {
        return {
            topic: "Microprocessors",
            question: "Within a microprocessor, what is the primary function of the Program Counter (PC)?",
            options: ["To count the number of errors generated", "To measure the clock frequency", "To count how many times the ALU has been used"],
            correct: "To hold the memory address of the next instruction to be fetched and executed"
            };
        },
            () => {
        return {
            topic: "Microprocessors",
            question: "What is the 'Accumulator' in a microprocessor's CPU?",
            options: ["A battery backup system", "A large capacitor for power filtering", "A heat sink"],
            correct: "A primary register used to store intermediate results of ALU operations"
            };
        },
            () => {
        return {
            topic: "Microprocessors",
            question: "What does the term 'Clock Speed' (measured in MHz or GHz) indicate regarding a microprocessor?",
            options: ["The rate at which the hard drive spins", "The speed at which data travels over the internet", "The time it takes to boot up"],
            correct: "The frequency of the internal oscillator that dictates how many instruction cycles the CPU can execute per second"
            };
        },
            () => {
        return {
            topic: "Microprocessors",
            question: "What happens when a microprocessor receives a valid 'Interrupt' signal?",
            options: ["It shuts down completely to prevent damage", "It deletes all data in the RAM", "It speeds up its clock frequency"],
            correct: "It pauses its current task, saves its state, and executes a specific Interrupt Service Routine (ISR)"
            };
        },
            () => {
        return {
            topic: "Microprocessors",
            question: "What is the purpose of the Instruction Decoder within the CPU?",
            options: ["To encrypt data before transmitting", "To translate English commands into binary", "To check for viruses in the code"],
            correct: "To interpret the fetched binary instruction code and generate the necessary control signals to execute it"
            };
        },
            () => {
        return {
            topic: "Microprocessors",
            question: "The complete sequence of fetching, decoding, and executing a single instruction is known as:",
            options: ["A boot sequence", "An interrupt sequence", "A macro operation"],
            correct: "A Machine Cycle (or Instruction Cycle)"
            };
        },
            () => {
        return {
            topic: "Microprocessors",
            question: "In microprocessor terminology, what is a 'Stack'?",
            options: ["A pile of printed circuit boards", "A queue of pending network messages", "A group of disconnected wires"],
            correct: "A designated area of RAM operating on a Last-In, First-Out (LIFO) basis, used to temporarily store register states or return addresses"
            };
        },
            () => {
        return {
            topic: "Microprocessors",
            question: "What happens during the 'Fetch' phase of a microprocessor instruction cycle?",
            options: ["The ALU performs a calculation", "The CPU writes data to the hard drive", "The system enters sleep mode"],
            correct: "The CPU reads the next instruction code from memory into its instruction register"
            };
        },
            () => {
        return {
            topic: "Fiber Optics",
            question: "What physical phenomenon causes light to remain trapped inside the core of a fiber optic cable?",
            options: ["Magnetic refraction", "Capillary action", "Electromagnetic shielding"],
            correct: "Total Internal Reflection"
            };
        },
            () => {
        return {
            topic: "Fiber Optics",
            question: "In a fiber optic cable, the core must have a refractive index that is:",
            options: ["Exactly the same as the cladding", "Lower than the cladding", "Constantly changing"],
            correct: "Higher than the refractive index of the cladding"
            };
        },
            () => {
        return {
            topic: "Fiber Optics",
            question: "What is a primary advantage of utilizing fiber optic data cables in modern aircraft avionics over traditional copper cables?",
            options: ["They can carry higher electrical voltages", "They are much easier to splice and repair", "They can be bent at sharp 90-degree angles"],
            correct: "They offer vastly higher bandwidth and are completely immune to electromagnetic interference"
            };
        },
            () => {
        return {
            topic: "Fiber Optics",
            question: "Which component acts as the light source in a typical high-speed avionics fiber optic transmitter?",
            options: ["A photodiode", "An incandescent bulb", "A fluorescent tube"],
            correct: "A Light Emitting Diode (LED) or Laser Diode"
            };
        },
            () => {
        return {
            topic: "Fiber Optics",
            question: "What component in a fiber optic receiver converts the incoming light pulses back into an electrical signal?",
            options: ["A transformer", "A logic gate", "An optical prism"],
            correct: "A Photodiode or Phototransistor"
            };
        },
            () => {
        return {
            topic: "Fiber Optics",
            question: "'Multimode' fiber optic cables are characterized by:",
            options: ["Having extremely thin cores suitable only for lasers", "Carrying electrical current alongside light", "Being completely rigid and inflexible"],
            correct: "Having a relatively large core diameter that allows multiple paths (modes) of light to travel simultaneously"
            };
        },
            () => {
        return {
            topic: "Fiber Optics",
            question: "What is the standard unit used to measure optical power loss (attenuation) in a fiber optic cable?",
            options: ["Ohms", "Volts", "Amperes"],
            correct: "Decibels (dB)"
            };
        },
            () => {
        return {
            topic: "Fiber Optics",
            question: "What is the primary physical purpose of the 'cladding' in a fiber optic cable?",
            options: ["To provide physical armor against crushing", "To conduct electricity for the transmitter", "To absorb stray light"],
            correct: "To provide a lower refractive index boundary that forces light to reflect back into the core"
            };
        },
            () => {
        return {
            topic: "Fiber Optics",
            question: "In fiber optics, what is 'dispersion'?",
            options: ["The physical breaking of the glass core", "The fading of the light source over time", "The melting of the plastic jacket"],
            correct: "The spreading out of light pulses as they travel down the fiber, limiting maximum data rate"
            };
        },
            () => {
        return {
            topic: "Fiber Optics",
            question: "When terminating or splicing a fiber optic cable, what is absolutely critical to ensure minimal signal loss?",
            options: ["Applying a heavy coat of solder", "Ensuring the cable is warm", "Grounding the connector to the airframe"],
            correct: "Ensuring the end faces are perfectly clean, polished, and squarely aligned"
            };
        },
            () => {
        return {
            topic: "Fiber Optics",
            question: "Why are fiber optic cables completely immune to Electromagnetic Interference (EMI) and High-Intensity Radiated Fields (HIRF)?",
            options: ["Because they are wrapped in heavy lead shielding", "Because they carry extremely high voltages", "Because they have a built-in error checking protocol"],
            correct: "Because they transmit data using photons (light) rather than electrons, and glass is an electrical insulator"
            };
        },
            () => {
        return {
            topic: "Fiber Optics",
            question: "Which connector type is specifically known for its precision in maintaining alignment and is commonly used in aircraft avionics for terminating fiber optic links?",
            options: ["BNC connector", "RJ-45 connector", "D-Subminiature connector"],
            correct: "ST, SC, or specialized aerospace MIL-spec physical contact connectors"
            };
        },
            () => {
        return {
            topic: "Electrostatic Sensitive Devices",
            question: "When handling Electrostatic Sensitive Devices (ESD) on an avionics workbench, what is the primary purpose of a grounded wrist strap?",
            options: ["To protect the technician from high voltage shocks", "To keep the technician's hands warm", "To provide a radio antenna for communication"],
            correct: "To safely and continuously bleed any static charge buildup from the technician's body to ground"
            };
        },
            () => {
        return {
            topic: "Electrostatic Sensitive Devices",
            question: "According to the textbook excerpt, how do AC Corona Ionisers neutralize static charges in the air?",
            options: ["By blowing highly compressed cold air", "By spraying a fine mist of water", "By absorbing dust particles"],
            correct: "By utilizing a high voltage step-up transformer to establish an intense electric field that ionizes air molecules"
            };
        },
            () => {
        return {
            topic: "Electrostatic Sensitive Devices",
            question: "Why do AC type ionisers typically utilize fast airflow velocity on an ESD workbench?",
            options: ["To cool down the circuit boards", "To dry out solder paste", "To increase the static charge"],
            correct: "To push the positive and negative ions away quickly and minimize their recombination loss"
            };
        },
            () => {
        return {
            topic: "Electrostatic Sensitive Devices",
            question: "When working with ESD-sensitive circuit boards, what type of packaging must be used for transport and storage?",
            options: ["Standard cardboard boxes", "Clear plastic ziplock bags", "Styrofoam packing peanuts"],
            correct: "Conductive or static-dissipative shielded bags (e.g., metallic grid bags)"
            };
        },
            () => {
        return {
            topic: "Electrostatic Sensitive Devices",
            question: "Which of the following actions is most likely to generate a massive, damaging triboelectric (static) charge?",
            options: ["Touching a grounded metal workbench", "Using a grounded soldering iron", "Leaving the component on an anti-static mat"],
            correct: "Unrolling standard plastic packaging tape or walking across a synthetic carpet"
            };
        },
            () => {
        return {
            topic: "Electrostatic Sensitive Devices",
            question: "How does the artificial ionisation of a tiny percentage of air molecules affect the static discharge time of a work environment?",
            options: ["It makes static discharge impossible", "It increases the discharge time to several hours", "It causes spontaneous combustion"],
            correct: "It dramatically reduces the static discharge time from hours down to seconds"
            };
        },
            () => {
        return {
            topic: "Software Management Control",
            question: "In modern aviation software management, what does the acronym 'LSP' stand for?",
            options: ["Line Standard Protocol", "Local System Program", "Light Signal Processor"],
            correct: "Loadable Software Part"
            };
        },
            () => {
        return {
            topic: "Software Management Control",
            question: "The aviation software standard document DO-178C deals primarily with:",
            options: ["The physical size of the computer chassis", "The electrical voltages of the data buses", "The training requirements for pilots"],
            correct: "Software Considerations in Airborne Systems and Equipment Certification"
            };
        },
            () => {
        return {
            topic: "Software Management Control",
            question: "What is the purpose of a Cyclic Redundancy Check (CRC) when uploading field loadable software to an aircraft computer?",
            options: ["To compress the file size", "To encrypt the software against hackers", "To translate the code into English"],
            correct: "To mathematically verify that the transferred software data is perfectly intact and uncorrupted"
            };
        },
            () => {
        return {
            topic: "Software Management Control",
            question: "What defines 'Configuration Control' in the context of aircraft avionics software?",
            options: ["Adjusting the brightness of the EFIS screens", "Setting the aircraft's autopilot parameters", "Choosing which language the FMS displays"],
            correct: "The strict administrative process of tracking, recording, and managing the exact hardware and software part numbers installed on the aircraft"
            };
        },
            () => {
        return {
            topic: "Software Management Control",
            question: "When transferring software updates directly to an aircraft via a portable data loader (PDL) using the ARINC 615 standard, what physical interface bus is primarily utilized?",
            options: ["USB", "Ethernet", "MIL-STD-1553"],
            correct: "ARINC 429"
            };
        },
            () => {
        return {
            topic: "Software Management Control",
            question: "In aircraft software design, what does 'Level A' software criticality indicate?",
            options: ["The software is for passenger entertainment only", "The software is in the beta testing phase", "The software has no safety impact"],
            correct: "A software failure would cause or contribute to a catastrophic failure condition for the aircraft"
            };
        },
            // --- BATCH GENERATED FROM CSV ---

    () => {
        return {
            topic: "Microprocessors",
            question: "What does Moore's Law observe regarding the evolution of integrated circuits?",
            options: ["The size of a transistor doubles every single year", "CPU clock speed doubles every decade", "Power consumption reduces by half every two years"],
            correct: "The number of transistors doubles roughly every two years"
            };
        },
            () => {
        return {
            topic: "Microprocessors",
            question: "In a CPU, what is the specific role of the Condition Code Register?",
            options: ["To store the address of the next instruction to be executed", "To interface the CPU directly to the external data bus", "To hold the operation code during the decoding process"],
            correct: "To hold bits representing the results of ALU operations"
            };
        },
            () => {
        return {
            topic: "Microprocessors",
            question: "During the generic instruction execution cycle, what occurs immediately after the 'Fetch' phase?",
            options: ["The operation is executed by the ALU", "The result is stored in the memory", "The program counter is reset to zero"],
            correct: "The control unit decodes the instruction"
            };
        },
            () => {
        return {
            topic: "Microprocessors",
            question: "Which type of instruction word contains no explicit address fields because the source and destination are implied?",
            options: ["Single Address Instruction", "Multi-Address Instruction", "Instruction Set Architecture"],
            correct: "Zero Address Instruction"
            };
        },
            () => {
        return {
            topic: "Computer Memory",
            question: "Which memory technology requires an external refresh circuit to periodically rewrite data to prevent its loss?",
            options: ["Static Random-Access Memory (SRAM)", "Magnetic Core Storage", "Read-Only Memory (ROM)"],
            correct: "Dynamic Random-Access Memory (DRAM)"
            };
        },
            () => {
        return {
            topic: "Computer Structure",
            question: "What term describes the digital logic that implements a specific Instruction Set Architecture (ISA)?",
            options: ["Bootstrap Loader", "Operating System", "Machine Language"],
            correct: "Microarchitecture"
            };
        },
            () => {
        return {
            topic: "Microprocessors",
            question: "Which component of a microprocessor acts as the 'accumulator'?",
            options: ["A non-user-accessible address buffer", "A register that points to the current stack location", "The circuit that generates the master clock frequency"],
            correct: "A register used to hold operands and results from the ALU"
            };
        },
            () => {
        return {
            topic: "Computer Structure",
            question: "In computer architecture, what is the primary function of the internal bus within a motherboard?",
            options: ["To connect peripheral devices such as hard discs and CD-ROMs", "To provide power to the cooling fans and supply module", "To convert serial data from I/O ports into parallel data"],
            correct: "To link parts of the computer to the CPU and main memory"
            };
        },
            () => {
        return {
            topic: "Microprocessors",
            question: "Which part of the Central Processing Unit (CPU) is responsible for interpreting instruction codes and generating timing signals?",
            options: ["The Arithmetic/Logic Unit (ALU)", "The Processor Registers", "The Internal Data Bus"],
            correct: "The Control Unit"
            };
        },
            () => {
        return {
            topic: "Computer Memory",
            question: "What is the primary advantage of Semiconductor Storage (Silicon Chips) compared to older technologies like Magnetic Core?",
            options: ["It is inherently non-volatile and retains data without power", "It uses vacuum tubes to increase the speed of thermionic emission", "It relies on mechanical switches to prevent spurious output"],
            correct: "It has high reliability and fast internal processing speeds"
            };
        },
            () => {
        return {
            topic: "Computer Memory",
            question: "Which type of memory allows data to be erased and reprogrammed using ultraviolet light?",
            options: ["Programmable Read-Only Memory (PROM)", "Magnetic Core Storage", "NAND Solid State Drive"],
            correct: "Erasable Programmable Read-Only Memory (EPROM)"
            };
        },
            () => {
        return {
            topic: "Computer Memory",
            question: "Why is RAM considered 'volatile' memory in aircraft computer systems?",
            options: ["It can be erased using a burst of ultraviolet light", "It cannot be changed once the manufacturer has programmed it", "It is susceptible to mechanical failure from high vibration"],
            correct: "It loses its stored contents when power is removed"
            };
        },
            () => {
        return {
            topic: "Numbering Systems",
            question: "What is the specific definition of a 'Nibble' in terms of binary data storage?",
            options: ["A sequence of 2 bits", "A sequence of 8 bits", "A single binary digit"],
            correct: "A sequence of 4 bits"
            };
        },
            () => {
        return {
            topic: "Numbering Systems",
            question: "In computer memory terminology, how many bytes are exactly contained in 1 Kilobyte (K)?",
            options: ["512 bytes", "1000 bytes", "2048 bytes"],
            correct: "1024 bytes"
            };
        },
            () => {
        return {
            topic: "Electronic Displays",
            question: "What is the purpose of the 'Aquadag' coating found inside older Cathode Ray Tubes (CRTs)?",
            options: ["To emit electrons via the principle of thermionic emission", "To provide the fluorescent material that glows on impact", "To house the three electron guns required for colour"],
            correct: "To eliminate the effects of secondary emission"
            };
        }
    ];

// REGISTER MODULE 5: Digital Techniques / Electronic Instrument Systems
if (typeof registerModule !== 'undefined') {
    registerModule(
        "Module 5: Digital Techniques / Electronic Instrument Systems",
        72, // Standard exam length
        function(count) {
            // Shuffle the pool
            const pool = [...digitalInstrumentGenerators];
            for (let i = pool.length - 1; i > 0; i--) {
                const j = Math.floor(Math.random() * (i + 1));
                [pool[i], pool[j]] = [pool[j], pool[i]];
            }
            
            // Generate Questions
            return pool.slice(0, count).map(gen => {
                const data = gen();
                
                // Compatibility for standard format
                let finalOptions = [...data.options, data.correct];
                
                // Shuffle Options safely
                for (let i = finalOptions.length - 1; i > 0; i--) {
                    const j = Math.floor(Math.random() * (i + 1));
                    [finalOptions[i], finalOptions[j]] = [finalOptions[j], finalOptions[i]];
                }
                
                return {
                    topic: data.topic || "Digital Techniques / Electronic Instrument Systems",
                    question: data.question,
                    img: data.img || null,
                    options: finalOptions,
                    correct: data.correct
                };
            });
        },
        `${digitalInstrumentGenerators.length} Scenarios (CASA B2-05)`
    );
}